name = "Smart-Pointers"
version = "2.3.0"
license = "BSD"
author = ["Damian Rouson, Karla Morris, Jim Xia, Wileam Phan, Brad Richardson, Tom Clune, Kareem Jabbar Weaver"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2020-2024 Sourcery Institute"
