@startuml

title Smart Pointers Class Diagram

hide empty members

abstract class sp_resource_t {
  {abstract} free()
}

class sp_reference_counter_t {
  - count_ : integer, pointer
  - object_ : sp_resource_t
  grab()
  release()
}

abstract class sp_smart_pointer_t {
  - counter_ : counter_t
  release_handle()
  start_counter()
}

sp_smart_pointer_t -up-|> sp_resource_t
sp_smart_pointer_t     *- sp_reference_counter_t
sp_reference_counter_t *- sp_resource_t

@enduml
