assert –
assert Interface
7 statements
Source File
interface
Calls
Called by
public pure module module subroutine assert(assertion, description) Implementation →
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: assertion
character(len=*), intent(in) :: description
Description
Error terminate on .false. assertion with the stop code given by description With IBM XL Fortran, the stop code is an integer due to for character stop codes being unsupported.
Call graph
assert calls assert
grab calls assert, grab
release calls assert, release
reference_count calls assert, reference_count